backend = "glx";

glx-swap-method = 2;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;

vsync = true;

unredir-if-possible = true;
unredir-if-possible-exclude = [];

fading = false;
shadow = false;
blur-background = false;

use-damage = true;
