"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "st"
diff-editor = ":builtin"

[aliases]
l = ["log"]
bl = ["bookmark", "list"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
pull = ["git", "fetch"]
push = ["util", "exec", "--", "uvx", "jj-pre-push", "push"]
pushnew = ["util", "exec", "--", "bash", "-c", 'jj push --named "$1"=${2-@-}', ""]
wc = ["log", "--stat", "-T", "builtin_log_compact_full_description"]

[fix.tools.1-ruff-lint]
command = ["uvx", "ruff", "check", "--fix", "--quiet", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.2-ruff-format]
command = ["uvx", "ruff", "format", "--stdin-filename=$path", "-"]
patterns = ["glob:'**/*.py'"]

[fix.tools.3-terraform-fmt]
command = ["terraform", "fmt", "-"]
patterns = ["glob:'**/*.tf'"]

[fix.tools.4-shfmt]
command = ["shfmt"]
patterns = ["glob:'**/*.sh'"]
