"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[template-aliases]
"format_timestamp(timestamp)" = "timestamp.ago()"

[ui]
default-command = "st"
diff-editor = ":builtin"

[aliases]
l = ["log"]
bl = ["bookmark", "list"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
fetch = ["git", "fetch"]
